name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Gets CMake
      uses: lukka/get-cmake@latest

    - name: Build hermite
      run: |
        mkdir build && cd build
        cmake .. -DHERMITE_BUILD_TESTING=ON -DHERMITE_BUILD_EXAMPLE=ON

    - name: Run Unit Tests
      run: |
        cd build && make
        ctest

